rules:
  - DOMAIN-SUFFIX,google.com,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,private_domain,ğŸ¯ ç›´è¿
  - RULE-SET,proxylite,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,youtube_domain,ğŸ“¹ YouTube
  - RULE-SET,netflix_domain,ğŸ¥ NETFLIX
  - RULE-SET,disney_domain,ğŸ¬ DISNEY
  - RULE-SET,gfw_domain,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,geolocation-!cn,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,cn_domain,ğŸ¯ ç›´è¿
  - RULE-SET,google_ip,ğŸš€ é»˜è®¤ä»£ç†,no-resolve
  - RULE-SET,netflix_ip,ğŸ¥ NETFLIX,no-resolve
  - RULE-SET,cn_ip,ğŸ¯ ç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}

rule-providers: 
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  proxylite: { <<: *class, url: "https://raw.githubusercontent.com/alterem/ClashRules/refs/heads/main/proxy.list"}
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  disney_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/disney.mrs"}
  gfw_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs"}
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}

proxy-groups:
  - {name: ğŸš€ é»˜è®¤ä»£ç†, type: select, proxies: [â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, DIRECT]}
  - {name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©, type: url-test, include-all: true, tolerance: 50, interval: 300}
  - {name: ğŸ“¹ YouTube, type: select, proxies: [ğŸš€ é»˜è®¤ä»£ç†, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹]}
  - {name: ğŸ¥ NETFLIX, type: select, proxies: [ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹]}
  - {name: ğŸ¬ DISNEY, type: select, proxies: [ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹]}
  - {name: ğŸ¯ ç›´è¿, type: select, proxies: [DIRECT, ğŸš€ é»˜è®¤ä»£ç†]}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, type: select, proxies: [ğŸš€ é»˜è®¤ä»£ç†, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, DIRECT]}
  
  # åœ°åŒºèŠ‚ç‚¹åˆ†ç»„
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)^(?=.*(æ¸¯|hk|HK|hongkong|hong kong))(?!.*(å›å›½|æ ¡å›­|æ¸¸æˆ|æ•™è‚²|ä¹…è™š|cn)).*$"}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)^(?=.*(ç¾|us|US|united states|unitedstates))(?!.*(å›å›½|æ ¡å›­|æ¸¸æˆ|æ•™è‚²|ä¹…è™š|cn)).*$"}
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)^(?=.*(æ–°åŠ å¡|sg|SG|singapore))(?!.*(å›å›½|æ ¡å›­|æ¸¸æˆ|æ•™è‚²|ä¹…è™š|cn)).*$"}
  - {name: ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)^(?=.*(åœŸè€³å…¶|tr|TR|turkey))(?!.*(å›å›½|æ ¡å›­|æ¸¸æˆ|æ•™è‚²|ä¹…è™š|cn)).*$"}
  - {name: ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, type: select, include-all: true}
